version: '3.6'

services:
  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    
  web:
    build: .
    command: 
    volumes:
      - .:/code
    environment:
    depends_on:
      - db
